### ISSUE TITLE
clone repos in a specific repo file

### ISSUE THREAD

**Issue by ShannonYLu** [Skyscanner/turbolift#119]
Hi team,

For the very useful feature of [working on multiple repo files](https://github.com/Skyscanner/turbolift/blob/main/README.md#working-on-multiple-repo-files), can `turbolift clone` also be made to take an additional repo file argument?

**Comment by Dan7-7-7** [comment]
hi @ShannonYLu, the alternative repo file should already work for `turbolift clone`. It was implemented across all commands. Thank you for raising this, it looks like we need to make it clearer in the readme - I'll add some more info there.

**Comment by sledigabel** [comment]
Addressed by #120
