### ISSUE TITLE
foreach handles arguments inconsistently

### ISSUE THREAD

**Issue by annettejanewilson** [Skyscanner/turbolift#135]
Prior to #132, the `foreach` command had the behaviour that it concatenates all remaining arguments with spaces and passes the result to `$SHELL -c` in each repository's directory.

Subsequent to that change, `foreach` now checks each argument for whether it contains spaces, and if it does, formats it as a Golang string literal, before concatenating all of them with spaces and passing them to `$SHELL -c` as before.

* This does not quote everything it should, such as empty arguments.
* This quotes things it should not, such as a single-argument shell script.
* We probably shouldn't rely on formatting as a Golang string literal to safely escape POSIX shell strings - it's the wrong tool for this purpose.

Previously, there were effectively two ways you could invoke the foreach command:
* Pass a single quoted argument containing a shell script, which might make use of pipes and redirection.
* Pass a single simple command with multiple arguments which are all non-empty and have no spaces.

The former of these is rendered impossible by the #132, since it applies another layer of quoting to the shell script. Note that such scripts were always intended to be allowed, as seen in [this comment][1]:
> Execute within a shell so that piping, redirection, etc are possible

If we are losing this ability to pass a shell script, I think it's debateable whether there's any point in running through a shell at all and having to worry about escaping characters. We only _need_ to quote characters because we pass them to a shell.

As noted earlier, the fix doesn't solve the problem that empty arguments are lost entirely, and it leaves many shell characters intact (notably `$` `(` `{` which may be interpreted inside of a string).

I suggest the following behaviour:

* An option `-c/--command` which takes a single argument, which is a shell script to be passed directly to the shell without quoting. Any subsequent arguments provided are passed as arguments to the shell script, unmodified.
* Use standard GNU processing of `--` as a marker that all remaining arguments are not to be processed as options.
* In the absence of `-c/--command`, all the arguments are passed unmodified to `exec.Execute`.

I am open to other suggestions. An even simpler approach would be not to implement a `-c/--command` at all and if users want to do that they can just invoke `turbolift foreach bash -c "blah blah blah"`. (That's not possible to do safely at present, since the unsafe quoting of the script may result in inappropriate expansion of variables and subprocesses at the wrong point.)

Some suggested test commands:

```
# Should emit an empty pair of brackets for the empty argument
printf '[%s]\n' 'one' '' 'three'

# Should wrap everything in a single pair of brackets
printf '[%s]\n' 'all one argument'

# Should show the numbers in reverse order
seq 4 | sort -rn

# Should not expand the environment variable
echo '$PATH'
```

[1]: https://github.com/jesusfcr/turbolift/blob/9c3342638b0c5d4561b11b5dc4babc405cf28f0e/cmd/foreach/foreach.go#L115

**Comment by rnorth** [comment]
#136 was released in 3.0.0 - should be resolved now!
