### ISSUE TITLE
`foreach` mode for `--failed` or `--succeeded`

### ISSUE THREAD

**Issue by rnorth** [Skyscanner/turbolift#143]
During #141 @Dan7-7-7 suggested having a flag so that `turbolift foreach` could be run just targeting repos that failed on the previous run. Combining a couple of ideas, I think it could be possible if foreach's file-based output uses timestamped temp directories, which would enable to tool to figure out which repos failed or succeeded on the preceding run.

**Comment by sledigabel** [comment]
We could retrieve the last one by creating a symlink called `last` during the preceeding foreach and point it to the tmpdir.

**Comment by sledigabel** [comment]
this `last` symlink would be at the root of the campaign.

**Comment by Dan7-7-7** [comment]
Implemented in #147
