### ISSUE TITLE
Consider setting up Homebrew distribution via a tap

### ISSUE THREAD

**Issue by rnorth** [Skyscanner/turbolift#43]
The installation instructions could be simplified greatly if we use Homebrew for distribution. Per discussions, it would be good to set up a private tap and configure `goreleaser` to keep it up to date.

We need to ensure that MacOS distribution works without Gatekeeper problems; I don't think that signing/notarizing the binaries should be required for brew installs, but this needs verification.

**Comment by sledigabel** [comment]
I think it's time to make it an official formula.
Perhaps even github pages.
