### ISSUE TITLE
Turbolift can't start when there's an empty line in repos.txt

### ISSUE THREAD

**Issue by kevinrobayna** [Skyscanner/turbolift#46]
![image](https://user-images.githubusercontent.com/5471469/118151601-b472e280-b40b-11eb-9594-1d2554e93d81.png)

I had a txt file that had an empty line in the end. I think the tools should be able to filter empty lines so that you could group repositories by org or something.

**Comment by kevinrobayna** [comment]
I think here is where we would need to filter is here https://github.com/Skyscanner/turbolift/blob/master/internal/campaign/campaign.go#L79

**Comment by rnorth** [comment]
Yeah, you're right, empty lines should be ignored. Would you like to try raising a PR for it? 🙂
