### ISSUE TITLE
New files are ignored by the commit command

### ISSUE THREAD

**Issue by lanwen** [Skyscanner/turbolift#53]
That's actually a feature of a `git commit -a`, however it's unexpected for a turbolift user, as it states that you don't have to do anything. Currently workaround is to `turbolift foreach -- git add -A`, but maybe that could be part of the commit command by default?

**Comment by sledigabel** [comment]
relates to #50

**Comment by sledigabel** [comment]
I believe this would be fixed by #51 @lanwen, forgot to close that ticket.
We fixed it by disabling the parsing for everything after the `foreach` command.

**Comment by lanwen** [comment]
@sledigabel not sure if I formulated the issue correctly, so will try to rephrase if it was understood right:
During the action I created a new file, which wasn't picked up by the turbolift, so I had to explicitly call git add as a separate step. If this step is not required anymore and turbolift works fine with new files by default - then all good!
