### ISSUE TITLE
Print out links to the pull requests created

### ISSUE THREAD

**Issue by gavingmiller** [Skyscanner/turbolift#58]
At the end of a PR run, it would be great if the links were printed from the PRs that were created. So the results could look like this:

```
$ turbolift create-prs
  OK   Reading campaign data
  OK   Pushing changes in org/repo-1 to origin
  OK   Creating PR in org/repo-1
  OK   PR created: https://github.com/org/repo-1/pull/163
  OK   Pushing changes in org/repo-2 to origin
  OK   Creating PR in org/repo-2
  OK   PR created: https://github.com/org/repo-2/pull/163
  OK   Pushing changes in org/repo-3 to origin
  OK   Creating PR in org/repo-3
  OK   PR created: https://github.com/org/repo-3/pull/163
  OK   turbolift create-prs completed (3 OK, 0 skipped)
  ```

Love the tool, and find it very useful!

**Comment by sledigabel** [comment]
Thanks for your feedback @gavingmiller. Definitely a good addition to the feature set

**Comment by JimNero009** [comment]
I've also come

**Comment by JimNero009** [comment]
Sorry, fat fingers!

**Comment by rnorth** [comment]
@gavingmiller Sorry for the extremely long time to resolve this, but we think this is now finally addressed. We took a slightly different approach, but now have the `turbolift pr-status --list` command which includes URLs for all PRs. Hopefully you're still finding turbolift useful and can benefit from this!
Thanks
