### ISSUE TITLE
turbolift clone/create-prs does not work in windows

### ISSUE THREAD

**Issue by kathrynallan** [Skyscanner/turbolift#69]
When doing a `turbolift clone` in a windows environment, it reports the following error:

` Executing: git [checkout -b C:\src\turbolift\campaignx] in work/xxx/xxxxxx
         fatal: 'C:\src\turbolift\campaignx' is not a valid branch name.
`
It does actually manage to clone the repositories, but when then trying `turbolift create-prs` it reports the following error:

`Executing: git [push -u origin C:\src\turbolift\campaign] in work/xxx/xxxxxxx
         fatal: invalid refspec 'C:\src\turbolift\campaign'
`

**Comment by sledigabel** [comment]
hi @kathrynallan sorry for the delay on this and thanks for reporting!

It appears `path.Base` does not handle Windows paths properly.
https://pkg.go.dev/path

We should try to use `filepath` instead

**Comment by sledigabel** [comment]
Hi @kathrynallan 👋 I've filed #71, hoping this would fix the problem you've kindly reported.
I've managed to make sure there are no regressions, but have been unable to test it on Windows.
Would you be able to test this for us?

**Comment by kathrynallan** [comment]
> Hi @kathrynallan 👋 I've filed #71, hoping this would fix the problem you've kindly reported. I've managed to make sure there are no regressions, but have been unable to test it on Windows. Would you be able to test this for us?

Sure, are you able to send me the binaries or do I need to build from the branch?

**Comment by sledigabel** [comment]
Hi @kathrynallan, It should be relatively straight forward to build from the branch.
If you run `make build` the bin should appear and will be ready to use

**Comment by kathrynallan** [comment]
> Hi @kathrynallan, It should be relatively straight forward to build from the branch. If you run `make build` the bin should appear and will be ready to use

When I try a make build on the branch I get the following error:

`cmd\init\init.go:19:2: package embed is not in GOROOT (c:\go\src\embed)`

**Comment by kathrynallan** [comment]
Hi @sledigabel, tested it and it's all working great - thanks!  Glad to be able to use this now - a really handy tool 😊

**Comment by sledigabel** [comment]
Fantastic to hear :-)
Thank you for your help in testing this too.
