### ISSUE TITLE
Collect errors and display nicely

### ISSUE THREAD

**Issue by rnorth** [Skyscanner/turbolift#7]
Turbolift currently runs multiple commands in series over the list of repositories, displaying stdout/stderr to the user but ignoring exit codes.

This can make it difficult for the user - they have to scour logs for failures.

We should collect errors (i.e. exit code != 0) and display a suitably formatted list at the end of execution.

**Comment by tekumara** [comment]
+1 even just having a list of names of repos that failed at the end, alongside the count, would be helpful
