### ISSUE TITLE
Add the "modify all PR descriptions" option (re-run the README.md)

### ISSUE THREAD

**Issue by sledigabel** [Skyscanner/turbolift#82]
It would be cool to be able to update the PR description once they are open.

**Comment by ignaciobolonio** [comment]
something similar to `turbolift foreach gh pr edit --body-file ../../../README.md` but this also included the PR title in the description

**Comment by rnorth** [comment]
Sounds good. Perhaps tack this onto the `update-prs` command via an extra flag? Something like `--update-title-and-description` (although that's a bit of a mouthful, it'd be accurate)...?

**Comment by rnorth** [comment]
Ooh, look!
https://github.com/Skyscanner/turbolift/issues/65#issuecomment-926712455

> `turbolift update-prs --amend-description   # Replaces the description, using current README.md`
