### ISSUE TITLE
[Question] What is the user account of the submitted PRs?

### ISSUE THREAD

**Issue by mdelapenya** [Skyscanner/turbolift#87]
Reading the code, it seems it's the current user in the terminal session, but I wonder if it's possible to configuring turbolift to use a machine account instead.

**Comment by rnorth** [comment]
Hi @mdelapenya 
Sorry for the super slow response; the answer is pretty simple: it is the user who is authenticated to `gh`. If you need to raise PRs with a different user, I think you'd just need:

* a `GITHUB_TOKEN` environment variable set to a token owned by the machine account
* if you're committing anything, you'd probably also want git to have been configured already with a sensible `user.name` and `user.email`

I hope that answers the question; I'll close the issue now.
