### ISSUE TITLE
Option for shallow clone for repos with large commit histories

### ISSUE THREAD

**Issue by nitrocode** [Skyscanner/turbolift#89]
It would be nice to have an option to do a shallow clone for quicker clones. This would allow us to grab for example, the last 30 commits per repo instead of the entire commit history

```sh
# maybe --shallow-clone which could default to 50 last commits
turbolift clone --shallow-clone
# provide the clone depth which could default to 50 or -1 to account for the default deep clone
turbolift clone --depth=50
```

https://www.perforce.com/blog/vcs/git-beyond-basics-using-shallow-clones
https://github.blog/2020-12-21-get-up-to-speed-with-partial-clone-and-shallow-clone/

Example

```sh
git clone -–depth [depth] [remote-url]
```

**Comment by rnorth** [comment]
I think this is a good suggestion. I think that, almost always, a shallow or low-depth clone would be fine, so this should be the default. I'd be inclined to not even have an option to pull a full clone: in the rare circumstances that one is needed, users could run `turbolift foreach git fetch --unshallow`.

Would you, or anybody else, like to raise a PR?
