### ISSUE TITLE
turbolift foreach --help doesn't work

### ISSUE THREAD

**Issue by AndrewASI** [Skyscanner/turbolift#96]
When I run `turbolift foreach --help` I expect to see the help of foreach command. Instead, turbolift runs standalone `--help` on all the repositories in the workspace, which obviously fails.

**Comment by sledigabel** [comment]
Thanks @AndrewASI for filing this.
We'll get this fixed.

**Comment by sledigabel** [comment]
@AndrewASI just to let you know, a PR is coming soon for this.

**Comment by sledigabel** [comment]
FYI, PR #98 should address this problem. Sorry for the delay in this @AndrewASI
